#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS $POSTGRES_SCHEMA;
    GRANT ALL ON SCHEMA $POSTGRES_SCHEMA TO $POSTGRES_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $POSTGRES_SCHEMA GRANT ALL ON TABLES TO $POSTGRES_USER;
EOSQL