services:
  users-service:
    build:
      context: .
      dockerfile: ./apps/services/users-service/Dockerfile.dev
    ports:
      - '3002:3002'
    volumes:
      - ./apps/services/users-service:/app
      - ./apps/services/users-service/node_modules:/app/node_modules
    command: npm run start:dev
    env_file: ./users-service/.env
    networks:
      - backend
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3002/app/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  gateway:
    build:
      context: .
      dockerfile: ./apps/services/users-service/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./app/services/gateway/gateway:/app
      - ./app/services/gateway/node_modules:/app/node_modules
    command: npm run start:dev
    env_file: ./gateway/.env
    networks:
      - backend
    depends_on:
      users-service:
        condition: service_healthy
      auctions-service:
        condition: service_healthy

  auctions-service:
    build:
      context: .
      dockerfile: ./apps/services/users-service/Dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - ./app/services/auctions-service:/app
      - ./app/services/auctions-service/node_modules:/app/node_modules
    command: npm run start:dev
    env_file: ./auctions-service/.env
    networks:
      - backend
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/app/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  auctions-client:
    build:
      context: .
      dockerfile: ./apps/services/users-service/Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - ./apps/services/auctions-client:/app
      - ./apps/services/auctions-client/node_modules:/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transport_auctions
    networks:
      - backend
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
      - ./redis/create-queues.sh:/docker-entrypoint-initdb.d/create-queues.sh
    command: ["/bin/bash", "-c", "redis-server --appendonly yes & sleep 5 && /docker-entrypoint-initdb.d/create-queues.sh && wait"]
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
