FROM node:22

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY pnpm-lock.yaml ./

COPY common/package.json ./common/
COPY users-service/package.json ./users-service/

RUN pnpm install

COPY common ./common
COPY users-service ./users-service

RUN cd common && pnpm build

EXPOSE 3002

CMD ["pnpm", "run", "start:dev"]