version: "3"

services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./apps/services/gateway/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

  auctions:
    container_name: auctions
    build:
      context: .
      dockerfile: ./apps/services/auctions/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    driver: bridge
