import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TopMenu } from "@/components/TopBar";
import "../globals.css";
import { auth0 } from "@/lib/auth0";
import { ApolloWrapper } from "@/lib/ApolloWrapper";



export const metadata: Metadata = {
  title: "Transport Auctions",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth0.getSession();

  return (
    <ApolloWrapper>
      <TopMenu />
      {session ? children : <h1>Authenticate</h1>}
    </ApolloWrapper>
  )
}
