import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TopMenu } from "@/components/TopBar";
import "../globals.css";
import { ApolloWrapper } from "@/lib/ApolloWrapper";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Transport Auctions",
    description: "Generated by create next app",
};

export default async function SignupLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (<section>
        <TopMenu />
        {children}
    </section>)
}
